services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

  product:
    build:
      context: .
      dockerfile: ./apps/product/Dockerfile
      target: development
    command: yarn start:dev product
    env_file:
      - ./apps/product/.env
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app

  review:
    build:
      context: .
      dockerfile: ./apps/review/Dockerfile
      target: development
    command: yarn start:dev review
    env_file:
      - ./apps/review/.env
    ports:
      - 3002:3002
    volumes:
      - .:/usr/src/app

  schedule:
    build: 
      context: .
      dockerfile: ./apps/schedule/Dockerfile
      target: development
    command: yarn start:dev schedule
    env_file:
      - ./apps/schedule/.env
    ports:
      - 3003:3003
    volumes:
      - .:/usr/src/app

  booking:
    build: 
      context: .
      dockerfile: ./apps/booking/Dockerfile
      target: development
    command: yarn start:dev booking
    env_file:
      - ./apps/booking/.env
    ports:
      - 3004:3004
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
    ports:
      - 27017:27017
