apiVersion: v1
kind: Service
metadata:
  labels:
    app: booking
  name: booking-http
spec:
  ports:
  - name: "http"
    port: 3004
    protocol: TCP
    targetPort: 3004
  selector:
    app: booking
  type: NodePort
