apiVersion: v1
kind: Service
metadata:
  labels:
    app: booking
  name: booking-tcp
spec:
  ports:
  - name: "tcp"
    port: 4004
    protocol: TCP
    targetPort: 4004
  selector:
    app: booking
  type: ClusterIP
