apiVersion: v1
kind: Service
metadata:
  labels:
    app: schedule
  name: schedule-http
spec:
  ports:
  - name: "http"
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: schedule
  type: NodePort
