apiVersion: v1
kind: Service
metadata:
  labels:
    app: product
  name: product-http
spec:
  ports:
  - name: "http"
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: product
  type: NodePort
