apiVersion: v1
kind: Service
metadata:
  labels:
    app: product
  name: product-tcp
spec:
  ports:
  - name: "tcp"
    port: 4001
    protocol: TCP
    targetPort: 4001
  selector:
    app: product
  type: ClusterIP
